version: '3.4'

services:
  conduit:
    image: conduit:vscode
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
